### ISSUE TITLE
your code is not working

### ISSUE THREAD

**Issue by hello4leaf** [TaylorPzreal/ngx-cropper#1]
![image](https://user-images.githubusercontent.com/11420861/30121881-d0db925a-9367-11e7-978e-c079589f79f7.png)

----------
I followed your "Usage" but did not get the results..

What should I do?

**Comment by TaylorPzreal** [comment]
@hello4leaf Could you show your test code?I want to see how you configured.

**Comment by amitmallick** [comment]
ngx-cropper.min.js not exit in ngx folder
